export interface Props {
  id: string;
  appletOnLoad?: () => void;
  appName?: string;
  width?: number;
  height?: number;
  material_id?: string;
  filename?: string;
  ggbBase64?: string;
  borderColor?: string;
  borderRadius?: number;
  enableRightClick?: boolean;
  enableLabelDrags?: boolean;
  enableShiftDragZoom?: boolean;
  showZoomButtons?: boolean;
  errorDialogsActive?: boolean;
  showMenuBar?: boolean;
  showToolBar?: boolean;
  showToolBarHelp?: boolean;
  customToolBar?: string;
  showAlgebraInput?: boolean;
  showResetIcon?: boolean;
  language?: string;
  country?: string;
  allowStyleBar?: boolean;
  randomize?: boolean;
  randomSeed?: number;
  useBrowserForJS?: boolean;
  showLogging?: boolean;
  capturingThreshold?: number;
  enableFileFeatures?: boolean;
  enableUndoRedo?: boolean;
  perspective?: string;
  enable3d?: boolean;
  enableCAS?: boolean;
  algebraInputPosition?: string;
  preventFocus?: boolean;
  scaleContainerClass?: string;
  autoHeight?: boolean;
  allowUpscale?: boolean;
  playButton?: boolean;
  scale?: number;
  showAnimationButton?: boolean;
  showFullscreenButton?: boolean;
  showSuggestionButtons?: boolean;
  showStartTooltip?: boolean;
  rounding?: string;
  buttonShadows?: boolean;
  buttonRounding?: number;
  buttonBorderColor?: string;
  editorBackgroundColor?: string;
  editorForegroundColor?: string;
  textmode?: boolean;
  showKeyboardOnFocus?: boolean|'auto';
  keyboardType?: string;
  transparentGraphics?: boolean;
  disableJavaScript?: boolean;
  detachedKeyboardParent?: boolean;
  //custom props
  debug?: boolean;
  reloadOnPropChange?: boolean;
  onReady?: () => void;
  code?: string;
  float?: string;
}
declare function Geogebra(props: Props): JSX.Element;

export default Geogebra;
